### ISSUE TITLE
SKU - Auto increment

### ISSUE THREAD

**Issue by SirSteve** [aimeos/ai-admin-jqadm#116]
As an admin, I want the SKU to auto-increment starting at 1 so that I do not have to maintain this field.

**Comment by aimeos** [comment]
That's a bit contrawise to the intention of the field because it should contain an unique article number. If you don't need and want that, you can overwrite the implementation and add a unique value yourself. An auto-increment value isn't possible because there's already one for the ID column but you can use a md5 hash of something for example
