### ISSUE TITLE
Additional Information in Orders

### ISSUE THREAD

**Issue by switch-cheehau** [aimeos/ai-admin-jqadm#195]
![image](https://user-images.githubusercontent.com/82187386/121721750-2deb1700-cb17-11eb-9892-6aecb3e3a580.png)

![image](https://user-images.githubusercontent.com/82187386/121721889-5541e400-cb17-11eb-89ab-9791c631328d.png)

I wish to have extra customisable fields in Orders.
It's useful for logistic/shipping purpose, special notes for internal usage that don't reveal to customer
It's just additional information for sellers that does not related to aimeos flow.
Seller should able to add/modify the key/value pair through API as well as admin panel.

Hope it make sense.
I can do a PR with guidance.

**Comment by aimeos** [comment]
Our suggestion would be to add that to the "Delivery" box because it's related to logistics/shipping (and the space you've marked will be occupied by the delivery address if available).

The delivery service can already store arbitrary type/code/value triples but only the code/value pairs are shown in the current panel. Nevertheless, you can add another option/value table which you can store with type "hidden". Then, they aren't shown to the customer.

The relevant lines are:
- https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/templates/order/item-standard.php#L662-L776
- https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/src/Admin/JQAdm/Order/Standard.php#L456-L493
- https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/src/Admin/JQAdm/Order/Standard.php#L546-L559

We would love to get an PR from you :-)

**Comment by switch-cheehau** [comment]
Ah, sorry. just realise the table mshop_order_base_service_attr.
I think it's good enough for now. 

I noticed i can put anything as <kbd>type</kbd> in mshop_order_base_service_attr table
![image](https://user-images.githubusercontent.com/82187386/121763064-c0b5a100-cb6b-11eb-9cc4-02f658a197c2.png)

and customer only able to see the information if the type = delivery or type = payment.

The behaviour is perfect for my usage.

Will there be any impact to put anything in <kbd>type</kbd> column in mshop_order_base_service_attr table?

**Comment by aimeos** [comment]
All lines with a type of NOT "hidden" will be shown in the frontend

**Comment by switch-cheehau** [comment]
I'll close this issue first as current behaviour is enough
