### ISSUE TITLE
 quantity blocked after error payment

### ISSUE THREAD

**Issue by Alessio8810** [aimeos/ai-admin-jqadm#208]
**Environment**
1. Version (e.g. 2021.10)
2. Integration (Laravel)
3. System (Windows)

if the user tries to pay but the payment fails for some reason, the quantity of the ordered product is blocked and is no longer available

**To Reproduce**
1. Go to 'product in shop'
2. Click on 'add to basket'
3. Select payment method
4. if payment fail, product quantity is "availability 0"

**Comment by aimeos** [comment]
Yes, that's intended because payment gateways can update the payment status later by an asynchronous request to checkout/update component. There's a job controller which releases blocked coupons/stocks and you should execute it regularly:
https://aimeos.org/docs/latest/laravel/setup/#every-hour

**Comment by Alessio8810** [comment]
I tried to run the job, apparently it seems to work but the product is out of stock.
also how do i choose for which site the job should be performed?

**Comment by aimeos** [comment]
The second parameter of `./artisan aimeos:jobs` allows you to pass a list of site codes:
https://aimeos.org/docs/latest/laravel/setup/#cronjobs

**Comment by Alessio8810** [comment]
I had missed this detail, thanks!
however, the problem of the product out of stock remains, even when starting the jobs

**Comment by aimeos** [comment]
Please note that there's a (configurable) grace period of 24 hours until orders will be finally removed and their stock and coupon codes released because payment gateways can send payment status updates later if something changes on their side.

Here's the configuration setting for the grace period:
https://aimeos.org/docs/2021.x/config/controller-jobs/order-cleanup/#keep-hours
