### ISSUE TITLE
text editor with poor options

### ISSUE THREAD

**Issue by Michi1978** [aimeos/ai-admin-jqadm#220]
the text editor for the item description doesn't allow different font size? and also no colored text? and also no headlines with different classification e.g. H1, H2, H3? this is also very imprtant for SEO purpose. this is really very very poor. also a text and html preview would be fine. woocoemmerce has a very fine text editor with all required functions.

**Comment by aimeos** [comment]
We use CKEditor 5 for texts: https://ckeditor.com/ckeditor-5/
It offers all you want but we ship a stripped configuration because editors usually don't know much about HTML structure and created invalid HTML with several H1 headings for example. Furthermore, allowing different font sizes and colored texts break the design.

You can adapt the offered editor features by overwriting these lines in your own extension:
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/js/admin.js#L29-L54
