### ISSUE TITLE
CMS Cataloglist bug

### ISSUE THREAD

**Issue by Ameeko** [aimeos/ai-admin-jqadm#226]
**Environment**
Latest version

**Describe the bug**
When I create a new page in the admin backend (CMS menu) 
and drag the products "Cataloglist" element into the content area, it shows nothing.
If I save the change and reopen this page, it shows nothing.
However, the change will be saved, if I open the page I created, 
the products (slick slider) will appear on the frontend.

If I drag a products "Cataloglist" element to the demo main page (/), 
the products will appear in the editor.

**If i delete the 3 products "Cataloglist" elements from the demo main page and save the changes, that page will also go bad.**

Screenshot:
![cataloglist01](https://user-images.githubusercontent.com/61547701/153766571-882bce6b-fcb5-456f-98e5-efecd57894db.jpg)

**Comment by aimeos** [comment]
The "Cataloglist" block only shows placeholders, not the rendered products because only the frontend knows how to render them correctly. If you remove the placeholders, nothing bad should happen in the frontend. In the latest version, the product limit is reduced to 3 products and the placeholders are re-inserted after saving.

**Comment by aimeos** [comment]
We've tested that too and it worked without problems.
Do you have any JS error in the browser console?
Did you update to the latest version (`composer req aimeos/ai-cms-grapesjs:2021.10.x-dev`)?

**Comment by Ameeko** [comment]
It doesn't work after the update.
The error only occurs if I first drop a container item into the editor, press the save button and then drop the products item.
Unfortunately there are no error messages on the console.

**Comment by aimeos** [comment]
We've found the problem now:
After updating GrapesJS from 0.17.25 to 0.17.29, styles can be added now for each component and GrapesJS also removes them if the component isn't there. As a result, the product list has been added to the editor but was not visible because the required styles has been removed before by GrapesJS. This is now fixed and you can test by updating to the latest commit using:
```
composer aimeos/ai-cms-grapesjs:2021.10.x-dev
```

**Comment by Ameeko** [comment]
It works.
Great, thank you!
