### ISSUE TITLE
Product price vue error

### ISSUE THREAD

**Issue by michalfeher** [aimeos/ai-admin-jqadm#48]
Hi, I am getting vue.js error when I click on Price tab in detail view. I am on 2018-07-x.dev. It worked in previous version.
![snip20180709_23](https://user-images.githubusercontent.com/7691204/42455814-8dcb4d30-8393-11e8-8ba2-584f4cd60f9f.png)
![snip20180709_24](https://user-images.githubusercontent.com/7691204/42455815-8debdd8e-8393-11e8-9266-5066f751363b.png)

**Comment by aimeos** [comment]
As there's no reference to a line in the JS file, the problem is somewhere in the item-price-standard.php template and it seems to depend on your data. Debugging Vue.JS templates is hard because there's no line given for the template where the error occurs.

Can you please edit the template, remove half of the code in the price item HTML, test if the error is still there and repeat that on the part where you still have the error until you found the line that causes the problem?

**Comment by michalfeher** [comment]
This is the difference I see.

First screenshot - I get JS error, second I dont (but the modal with price form wont appear either).
![snip20180709_27](https://user-images.githubusercontent.com/7691204/42463293-ff329728-83a5-11e8-9c3c-a1f7e8698029.png)
![snip20180709_28](https://user-images.githubusercontent.com/7691204/42463295-ff5260e4-83a5-11e8-8e4c-e686e857d7ab.png)

**Comment by aimeos** [comment]
Sorry, doesn't help. What do you have to remove until (some) content of the price tab appears?

**Comment by michalfeher** [comment]
Even if I replace the whole item-price-standard.php file, the tab content wont show. I guess other files will have to be replaced too. I could only get rid of the JS error.
Cant you reproduce this issue on your side?

**Comment by aimeos** [comment]
No, we can't because it seems to depend on your data. What is the last tab where content is shown? Text or image?

**Comment by michalfeher** [comment]
Text is the last one working. In selection products however neither texts or images are working

**Comment by aimeos** [comment]
If you remove all input fields in the item-price-standard.php template, does it then work?

**Comment by michalfeher** [comment]
no, only when I remove everything in item-price-standard.php. if I only remove input fields, I still get js error.

**Comment by aimeos** [comment]
What if you remove the whole block?
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/templates/product/item-price-standard.php#L29-L46

If it works, the problem is somewhere there, if not then the problem could be here:
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/templates/product/item-price-standard.php#L29-L46

or (unlikely) here:
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/templates/product/item-price-standard.php#L29-L46

Can you also post an excerpt of the JSON data?
https://github.com/aimeos/ai-admin-jqadm/blob/master/admin/jqadm/templates/product/item-price-standard.php#L22

**Comment by michalfeher** [comment]
I think you accidentally copied one link 3 times.

here are the json data:
![image](https://user-images.githubusercontent.com/7691204/42747852-4bf2d964-88de-11e8-84d2-cb14053ee2a1.png)

**Comment by aimeos** [comment]
The JSON data seems to be OK. It contains the data of one price and one list item referencing the price. Where do you think is data added three times?

**Comment by michalfeher** [comment]
hm, I run composer update again and now it seems all working. not sure where the problem was though :/
anyway, thanks for your support and help.

**Comment by aimeos** [comment]
Then it was a problem within the selection panel which should now be faster and renders entries in linear time

**Comment by michalfeher** [comment]
could be. and yes I can see now that the load time of product with 400+ variants has significantly decreased. good job!
