### ISSUE TITLE
saveItem is called twice on Product save action

### ISSUE THREAD

**Issue by mfcanovas** [aimeos/ai-admin-jqadm#63]
**Environment**
1. 2018.10.2 
2. Laravel
3. Linux

**Describe the bug**
Product is being saved two times on the save action in [_Aimeos\Admin\JQAdm\Product\Standard_ ](https://github.com/aimeos/ai-admin-jqadm/blob/2b103e55f7d27ead2b2dbd5a5be97a93afa675a3/admin/jqadm/src/Admin/JQAdm/Product/Standard.php#L224)class. _fromArray_ method is called on line [234](https://github.com/aimeos/ai-admin-jqadm/blob/2b103e55f7d27ead2b2dbd5a5be97a93afa675a3/admin/jqadm/src/Admin/JQAdm/Product/Standard.php#L234) and it saves the item on line [545](https://github.com/aimeos/ai-admin-jqadm/blob/2b103e55f7d27ead2b2dbd5a5be97a93afa675a3/admin/jqadm/src/Admin/JQAdm/Product/Standard.php#L545). Then in line [241](https://github.com/aimeos/ai-admin-jqadm/blob/2b103e55f7d27ead2b2dbd5a5be97a93afa675a3/admin/jqadm/src/Admin/JQAdm/Product/Standard.php#L241) saveItem is called again

**To Reproduce**
1. Try to debug save product action and you will see saveItem called twice

**Expected behavior**
saveItem should be called only one time. 

**Additional context**
I have a decorator which triggers some actions when saveItem is called. Now I'm getting duplicate actions

**Comment by aimeos** [comment]
That's true because for some data we need the product ID e.g. for saving the catalog<->product reference. Therefore, the basic product item is saved first, then the sub-panels add their data or store references in foreign domains (already requiring the product ID) and at the end the product including all data is saved again.

It's also not a big performance problem because the product item itself keeps unchanged and therefore won't be sent again to the database. The only additional improvement might be to store the item in `fromArray()` only if it's a new one. This will prevent NoSQL systems to store the document twice if it already has an ID.

**Comment by aimeos** [comment]
Optimized by https://github.com/aimeos/ai-admin-jqadm/commit/05b0561ac2188041448f81833b91c8563d674828
