### ISSUE TITLE
Can't set category to product

### ISSUE THREAD

**Issue by noll1** [aimeos/ai-admin-jqadm#74]
**Environment**
1. Version: ai-admin-jqadm 2018.10.9; aimeos-core 2018.10.11
2. Integration: TYPO3 v9.5.2 LTS
3. System: Ubuntu 18.04.1

**Describe the bug**
I can't select a category in a product.
When I enter a category name I get no dropdown and after leaving the textbox the entered text dissapears.

**To Reproduce**
1. Try to set a property to a product.

**Comment by aimeos** [comment]
You are talking first about categories, than about properties. If your problem is related to categories, do you have categories in the catalog panel?

If there's no drop-down with categories you can select from, the entered text will disappear for sure because only selected categories have the ID that's required.

**Comment by noll1** [comment]
Sorry, I mean categories all the time.

I explain it a little more detailed:
I've installed aimeos 18.10.02 from TER in a fresh Typo3 v9.5.2 environment.
To the demo products I can set categories by clicking the small arrow on the right side and select a category from upcoming list (e.g. "Home").
Now I replaced the folders "ai-admin-jqadm" and "aimeos-core " in my Typo3 aimeos extension from current master branch.
After that it is no longer possible to add a category like the same way above described.
When I click the small arrow on the right side there is no list coming up. 
Before it was also possible to enter the first chars of the category which I want to have (e.g. "Ho") and a list with suitable categories appears.
That feature is missing after the update, too.

**Comment by aimeos** [comment]
Using parts from dev-master in combination with 18.10 doesn't work because the versions must fit together. You can only use code from 2018.10 branch.

We want to release a new 18.10 version as soon as we are able to upload the new Aimeos extension to the TER again. We highly suggest to use that one for further tests then. In the meantime, you can use this package: https://aimeos.org/fileadmin/download/aimeos_18.10.3.zip

**Comment by noll1** [comment]
Thanks for the explanation. I didn't realize that.

**Comment by noll1** [comment]
First of all thank you for the awesome support.
The pre version helps me a lot.

Thanks for the explanation. I didn't realize that.
Can you explain what I should consider when building my own version?
Is it enough to use only the 2018.10 branches of all extensions instead of the master branches?

**Comment by aimeos** [comment]
Yes, you can use the 2018.10 branches of the composer packages if you need fixes that are not tagged in a release version yet.
