### ISSUE TITLE
Partial refund on orders

### ISSUE THREAD

**Issue by khalidbashirbajwa** [aimeos/ai-admin-jqadm#91]
**Is your feature request related to a problem?**
We have implemented a shop using Aimeos. In the normal flow customer buys multiple products. Sometimes some of the products in the order are not available and the customer has to be refunded the Amount for only items that are not available. Hence a partial refund. There is no provision in the current system to track or issue partial refunds

**Describe the solution you'd like**
There should be a facility of partial refund on orders. In case of a partial refund the customer should be notified via Email about the items that he got refund against and the amount of the refund.

**Describe alternatives you've considered**
Currently we use MS Excel to manually track our orders

**Additional context**
None

**Comment by aimeos** [comment]
Returns and refunding is out of scope of Aimeos as it's core domain is presenting and selling products but not order management besides from basic stuff. Also, refunds have to be done in the interface of the payment provider most of the time. You can also use specialized SaaS services for return&refund if your sales outgrow Excel based handling.

Nevertheless, you can set the delivery status to "deleted" or "returned" depending on your case and this will automatically send an e-mail to the customer if the "order/email/delivery" job is executed regularly. The delivery status for each product is shown in e-mails since Aimeos 2019.07
